name: badminton_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8

  # --- Firebase ---
  firebase_core: ^3.10.1
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.2
  # firebase_storage: ^12.4.10
  flutter_map: ^7.0.0
  latlong2: ^0.9.1

  # --- LOCATION (GPS) ---
  geolocator: ^13.0.1
  permission_handler: ^11.3.1

  # --- Utilities & State Management ---
  image_picker: ^1.0.7
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  fl_chart: ^0.70.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
