// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_IsVLvZ4xloW17TDENbFmdCCg9I8qY8s',
    appId: '1:798972746133:web:4a6554ab7517216a83be9c',
    messagingSenderId: '798972746133',
    projectId: 'badminton-community-app',
    authDomain: 'badminton-community-app.firebaseapp.com',
    storageBucket: 'badminton-community-app.firebasestorage.app',
    measurementId: 'G-SJQG2E7D33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfq0WglrskLBdSQ0afezDb6tMbh3mwJE8',
    appId: '1:798972746133:android:5756eaa97adfd41183be9c',
    messagingSenderId: '798972746133',
    projectId: 'badminton-community-app',
    storageBucket: 'badminton-community-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7HZjEsoro_Km1UUnc9rJ6QcSMwdpx_fI',
    appId: '1:798972746133:ios:c2f03056bb495b5683be9c',
    messagingSenderId: '798972746133',
    projectId: 'badminton-community-app',
    storageBucket: 'badminton-community-app.firebasestorage.app',
    iosBundleId: 'com.badminton.app.badmintonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7HZjEsoro_Km1UUnc9rJ6QcSMwdpx_fI',
    appId: '1:798972746133:ios:c2f03056bb495b5683be9c',
    messagingSenderId: '798972746133',
    projectId: 'badminton-community-app',
    storageBucket: 'badminton-community-app.firebasestorage.app',
    iosBundleId: 'com.badminton.app.badmintonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_IsVLvZ4xloW17TDENbFmdCCg9I8qY8s',
    appId: '1:798972746133:web:cd970c02accf983283be9c',
    messagingSenderId: '798972746133',
    projectId: 'badminton-community-app',
    authDomain: 'badminton-community-app.firebaseapp.com',
    storageBucket: 'badminton-community-app.firebasestorage.app',
    measurementId: 'G-SEQEHTFM2K',
  );
}
